name = "Hyde-X"
license = "MIT"
licenselink = "https://github.com/zyro/hyde-x/LICENSE"
description = "An elegant open source and mobile first theme, extended with new integrations and layout improvements"
homepage = "http://jlopezsi.github.io"
tags = ["blog", "technical", "personal"]
features = ["blog", "technical", "personal"]

[author]
    name = "Jordi López"
    homepage = "http://jlopezsi.github.io"

# If Porting existing theme
[original]
    author =  "poole"
    homepage = "http://hyde.getpoole.com"
    repo = "https://github.com/poole/hyde"
